comment:
  behavior: default
  layout: reach, diff, flags, files, components
  require_base: false
  require_changes:
  - 0
  require_head: true
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    patch:
      default:
        target: 90.0
    project:
      default:
        target: auto
        threshold: 1.0
flag_management:
  default_Rules:
    carryforward: true
    statuses:
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  individual_flags:
  - name: backend
    carryforward: true
    paths:
    - ^backend/.*
    statuses:
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  - name: caching_celery_redis  
    carryforward: true
    paths:
    - ^backend/apps/core/.*
    statuses:
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  - name: credits
    carryforward: true
    paths:
    - ^backend/apps/credits/.*
    statuses:  
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  - name: monitoring
    carryforward: true
    paths:
    - ^backend/apps/monitoring/.*
    statuses:  
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  - name: stripe
    carryforward: true
    paths:
    - ^backend/apps/stripe_home/.*
    statuses:  
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  - name: users
    carryforward: true
    paths:
    - ^backend/apps/users/.*
    statuses:
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  - name: supabase_home
    carryforward: true
    paths:
    - ^backend/apps/supabase_home/.*
    statuses:  
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  - name: core
    carryforward: true
    paths:
    - ^backend/core/.*
    statuses:  
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
# Component configuration for more flexible reporting
component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 1.0
  individual_components:
    - component_id: app_core
      name: Core
      paths:
        - backend/core/.*
    - component_id: app_users
      name: Users
      paths:
        - backend/apps/users/.*
    - component_id: app_monitoring
      name: Monitoring
      paths:
        - backend/apps/monitoring/.*
    - component_id: app_caching
      name: Caching
      paths:
        - backend/apps/core/.*
    - component_id: app_stripe
      name: Stripe Integration
      paths:
        - backend/apps/stripe_home/.*
    - component_id: app_supabase
      name: Supabase Integration
      paths:
        - backend/apps/supabase_home/.*
    - component_id: app_credits
      name: Credits System
      paths:
        - backend/apps/credits/.*
    - component_id: apis
      name: API Components
      paths:
        - backend/.*/api/.*
    - component_id: tests
      name: Test Coverage
      paths:
        - backend/.*/tests/.*
ignore:
- (?s:.*/migrations/.*)\Z
- (?s:.*/admin\.py)\Z
- (?s:.*/__init__\.py)\Z
- (?s:.*/apps\.py)\Z