comment:
  behavior: default
  layout: reach, diff, flags, files
  require_base: false
  require_changes:
  - 0
  require_head: true
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    patch:
      default:
        target: 90.0
    project:
      default:
        target: auto
        threshold: 1.0
flag_management:
  default_Rules:
    carryforward: true
    statuses:
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  individual_flags:
  - name: backend
    carryforward: true
    paths:
    - ^backend/.*
    statuses:
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  - name: caching_celery_redis  
    carryforward: true
    paths:
    - ^backend/apps/core/.*
    statuses:
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  - name: credits
    carryforward: true
    paths:
    - ^backend/apps/credits/.*
    statuses:  
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  - name: monitoring
    carryforward: true
    paths:
    - ^backend/apps/monitoring/.*
    statuses:  
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  - name: stripe
    carryforward: true
    paths:
    - ^backend/apps/stripe_home/.*
    statuses:  
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  - name: users
    carryforward: true
    paths:
    - ^backend/apps/users/.*
    statuses:
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  - name: supabase_home
    carryforward: true
    paths:
    - ^backend/apps/supabase_home/.*
    statuses:  
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
  - name: core
    carryforward: true
    paths:
    - ^backend/core/.*
    statuses:  
    - target: auto
      threshold: 1.0
      type: project
    - target: 80.0
      type: patch
ignore:
- (?s:.*/migrations/.*)\Z
- (?s:.*/admin\.py)\Z
- (?s:.*/__init__\.py)\Z
- (?s:.*/apps\.py)\Z